SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO ad_campaign(id,
                        name,
                        ad_format,
                        num_impressions,
                        start_date,
                        end_date,
                        impressions_shown,
                        ad_server_id)
     VALUES (1,
             'Gillette',
             'TOP_BANNER',
             300,
             '2016-09-01',
             '2016-11-01',
             0,
             1);INSERT INTO ad_campaign(id,
                        name,
                        ad_format,
                        num_impressions,
                        start_date,
                        end_date,
                        impressions_shown,
                        ad_server_id)
     VALUES (2,
             'McDonalds',
             'TOP_BANNER',
             500,
             '2016-10-01',
             '2016-11-01',
             0,
             1);INSERT INTO ad_campaign(id,
                        name,
                        ad_format,
                        num_impressions,
                        start_date,
                        end_date,
                        impressions_shown,
                        ad_server_id)
     VALUES (3,
             'Microsoft',
             'TOP_BANNER',
             200,
             '2016-09-15',
             '2016-10-15',
             0,
             1);INSERT INTO ad_campaign(id,
                        name,
                        ad_format,
                        num_impressions,
                        start_date,
                        end_date,
                        impressions_shown,
                        ad_server_id)
     VALUES (4,
             'Apple',
             'INTERSTITIAL',
             500,
             '2016-09-01',
             '2016-09-30',
             0,
             1);INSERT INTO ad_campaign(id,
                        name,
                        ad_format,
                        num_impressions,
                        start_date,
                        end_date,
                        impressions_shown,
                        ad_server_id)
     VALUES (5,
             'AT&T',
             'HOVER',
             250,
             '2016-10-01',
             '2016-12-30',
             0,
             1);INSERT INTO ad_server(id, name, serving_strategy)
     VALUES (1, 'Round Robin', 'ROUND_ROBIN_INDIVIDUAL_REQUEST');INSERT INTO ad_server(id, name, serving_strategy)
     VALUES (2, 'Attempt Even', 'ATTEMPT_EVEN');SET FOREIGN_KEY_CHECKS = 1;COMMIT;